# Numpy
the core of many tools,powerful arrays as a data structure
## the resorce C code:
```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

In [1]:
import numpy as np

### create arrays

In [5]:
print(np.array([1,2,3],dtype='float32'))
print(np.array([range(i,i+3) for i in [2,4,6]]))
print(np.zeros((10,5),dtype=int))
print(np.ones((2,3)))
print(np.full(2,3),9)
print(np.arange(0,20,2)) #from 0 to 20,every 2 steps
print(np.linspace(0,1,5)) #from 0 to 1, 5 numbers

[1. 2. 3.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[3 3] 9
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


1. actually,we transform a kind of data structure into array.
2. we use an array for the size,'dtype' for the data type.
3. as for arange,linspace: it only come as form of a vector,need to be reshape to a certain structure

### random number

In [ ]:
np.random.seed(42) # a start for recurrence
print(np.random.randint(10,size=(2,3))) # generate natural number from 0 to 10,in size of (2,3)
print(np.random.random((2,3))) # generate any 0<=x<=1 
print(np.random.noraml(0,1,(3,3))) # normal distribution average 0,variance 1

### index