# Numpy
the core of many tools,powerful arrays as a data structure
## the resorce C code:
```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

In [7]:
import numpy as np

### create arrays

In [8]:
print(np.array([1,2,3],dtype='float32'))
print(np.array([range(i,i+3) for i in [2,4,6]]))
print(np.zeros((10,5),dtype=int))
print(np.ones((2,3)))
print(np.full(2,3),9)
print(np.arange(0,20,2)) #from 0 to 20,every 2 steps,default as for 0 to n every step
print(np.linspace(0,1,5)) #from 0 to 1, 5 numbers

[1. 2. 3.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[3 3] 9
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


1. actually,we transform a kind of data structure into array.
2. we use an array for the size,'dtype' for the data type.
3. as for arange,linspace: it only come as form of a vector,need to be reshape to a certain structure

### random number

In [9]:
np.random.seed(42) # a start for recurrence
print(np.random.randint(10,size=(2,3))) # generate natural number from 0 to 10,in size of (2,3)
print(np.random.random((2,3))) # generate any 0<=x<=1 
print(np.random.normal(0,1,(3,3))) # normal distribution average 0,variance 1

[[6 3 7]
 [4 6 9]]
[[0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449]]
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]


### index
very similar to normal data structure,use : to describe the 

In [10]:
x=np.arange(10)
print(x[:5])
print(x[5:])
print(x[3::2])
print(x[3:-1])
print(x[::-1]) #reverse the array
y=x.reshape((2,5)) #change the arrange of the data
print(y[1,:])
print(y[0])
y1=y[:1,:1]
y1[0,0]=1
print(y) # it represent a kind of copy, change the origin one
# Fancy indexing:use array as index
x=np.arange(10)
i=np.array([2,1,4])
x[i]-=2
print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[3 5 7 9]
[3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]
[5 6 7 8 9]
[0 1 2 3 4]
[[1 1 2 3 4]
 [5 6 7 8 9]]
[ 0 -1  0  3  2  5  6  7  8  9]


### operation among arraies

In [11]:
z=x[::-1]
print(np.vstack([x,z]))
print(np.hstack([x,z]))
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)
x1,x2,x3=np.hsplit(x,[3,5])
print(x1,x2,x3)
# assemble and split the specific array,generally we use v(vehicle),h(horizontal) to describe the way we operate the array.

[[ 0 -1  0  3  2  5  6  7  8  9]
 [ 9  8  7  6  5  2  3  0 -1  0]]
[ 0 -1  0  3  2  5  6  7  8  9  9  8  7  6  5  2  3  0 -1  0]
[ 0 -1  0] [3 2] [5 6 7 8 9]
[ 0 -1  0] [3 2] [5 6 7 8 9]


### caulculation
UFuncs:vectorized operation(we automatically transform number or vector to matrix for data analysis,simplify the loop)

In [12]:
print("x+2=",x+2)
print("|x-5|=",abs(x-5))
# more kinds of functions: exp,log,trigo(specific funcs need special )
print("exp(x)=",np.expm1(x),"tan(x)=",np.tan(x),"log2(x+1)=",np.log(x+1))
# specifying output
z=np.zeros(20)
np.multiply(x,10,out=z[::2])
# aggregates (reture the result)
x=np.arange(6)
print(np.add.reduce(x))
print(np.add.accumulate(x))
# outer products (can be used for vector)
print(np.multiply.outer(x,x))

x+2= [ 2  1  2  5  4  7  8  9 10 11]
|x-5|= [5 6 5 2 3 0 1 2 3 4]
exp(x)= [ 0.00000000e+00 -6.32120559e-01  0.00000000e+00  1.90855369e+01
  6.38905610e+00  1.47413159e+02  4.02428793e+02  1.09563316e+03
  2.97995799e+03  8.10208393e+03] tan(x)= [ 0.         -1.55740772  0.         -0.14254654 -2.18503986 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566] log2(x+1)= [0.               -inf 0.         1.38629436 1.09861229 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
15
[ 0  1  3  6 10 15]
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]


C:\Users\bytt\AppData\Local\Temp\ipykernel_8324\2213413907.py:4: RuntimeWarning: divide by zero encountered in log
  print("exp(x)=",np.expm1(x),"tan(x)=",np.tan(x),"log2(x+1)=",np.log(x+1))


### Aggregations
some statistic values for data

In [19]:
print(np.sum(x))
print(np.min(x),np.max(x))
print(x[np.newaxis,:].max(axis=1))

15
1 5
[5]


some useful aggregation funcs
| 函数名称      |   NaN安全版本  | 说明                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | 计算总和                       |
| ``np.prod``       | ``np.nanprod``      | 计算乘积                   |
| ``np.mean``       | ``np.nanmean``      | 计算平均值                      |
| ``np.std``        | ``np.nanstd``       | 计算标准差                    |
| ``np.var``        | ``np.nanvar``       | 计算方差                              |
| ``np.min``        | ``np.nanmin``       | 计算最小值                            |
| ``np.max``        | ``np.nanmax``       | 计算最大值                            |
| ``np.argmin``     | ``np.nanargmin``    | 寻找最小值的序号                   |
| ``np.argmax``     | ``np.nanargmax``    | 寻找最大值的序号                   |
| ``np.median``     | ``np.nanmedian``    | 计算中位值                    |
| ``np.percentile`` | ``np.nanpercentile``| 计算百分比分布的对应值     |
| ``np.any``        | N/A                 | 是否含有True值        |
| ``np.all``        | N/A                 | 是否全为True值        |


### broadcast
the extension of normal
rule:
1. if 2 array have different dimensions, the one with fewer will expend on its left size with 1.  
((1,1),3 $\to$ (1,1),(1,3))
2. if the 2 doesn't match, the 1 in the dimension will stretch to match the other  
((1,1),(1,3) $\to$ ((1,3) $\times 2$ ))
3. if the operation above failed, than will generate a false   
(2,4 $\to$ false)  
some explain:we can see it geometrically, 2 dimension is a kind of 3 with 1 in the first dimension.

In [16]:
x=np.arange(3)
y=x.reshape((3,1))
print(x+y)
# a way to expand : newaxis(add 1 dimension to place needed),
z=np.hstack([y,y])
x[:,np.newaxis]+z

[[0 1 2]
 [1 2 3]
 [2 3 4]]


array([[0, 0],
       [2, 2],
       [4, 4]])

In [17]:
#boolen logic: the further utility of broadcast,return boolen array
print(x==3)
# usually we use funcs to demonstrate the situation of boolen value
print(np.sum(x==3),np.any(x<=3))
print(np.any(x>1)&np.all(x<4))
# moreover: to give out all the values that fit the requirement
print(x[x>1])

[False False False]
0 True
True
[2]


### sorting
provide different sorting criteria, depend on different needs
we use normal sort for change,argsort for find the index

In [22]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x)) # return result
i=np.argsort(x) #return index
print(i,x[i[1]],x[i[4]])
print(np.partition(x,2)) #only need to separate into 2 part, the smaller 2 in the left
y=np.random.randint(0,10,(4,6))
print(np.sort(y,axis=0))
print(np.sort(y,axis=1))
print(np.partition(y,2,axis=1))

[1 2 3 4 5]
[1 0 3 2 4] 2 5
[1 2 3 4 5]
[[0 1 1 1 3 1]
 [5 3 4 3 4 1]
 [8 5 9 3 5 6]
 [9 7 9 7 7 7]]
[[0 1 1 3 3 7]
 [1 3 5 5 5 9]
 [1 3 6 7 9 9]
 [1 4 4 7 7 8]]
[[0 1 1 7 3 3]
 [1 3 5 9 5 5]
 [1 3 6 9 7 9]
 [1 4 4 8 7 7]]


### Structured array
similar to panda's dataframe, work as multiply data form

In [23]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')}) #create with 
print(data.dtype)
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)
# referring to specific data
print(data['name'])
print(data[-1]['age'])
print(data[data['age']<30]['name'])

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
['Alice' 'Bob' 'Cathy' 'Doug']
19
['Alice' 'Doug']


## summary for Numpy
Numpy is a kind of library that can be used to initially process data.   
To be brief, Numpy has the ability as followed:   
1. create random array
2. use broadcast to operate array, connect or split it.
3. use funcs to do feature work, find out the sum,min,max or so.
4. use index to find out the specific data(fancy indexing)
5. use sort,partition to arrange the array
6. use dictionary-like arrays to restore data(can be easily replaced by pandas)

# Pandas
provide DataFrame, more friendly to sheet that are more common in normal research  

In [24]:
import pandas as pd

### create and visit

In [25]:
#Series
# normal Series:index or value
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data.values,data[1:3])
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)
# similar to dictionary
grade={'a':100,'b':99,'c':99}
g=pd.Series(grade)
print(g['a'],g['a':'c'])
# create :index,dictionary
print(pd.Series(grade,index=['a','c']))
# the Series can be seen as dict, with key and only one value.index determine the order

[0.25 0.5  0.75 1.  ] 1    0.50
2    0.75
dtype: float64
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
100 a    100
b     99
c     99
dtype: int64
a    100
c     99
dtype: int64


In [26]:
# DataFrame
# the combination of Series 
num={'a':'1','b':2,'c':3}
sub=pd.DataFrame({'grade':g,'number':pd.Series(num)})
print(sub,sub.index,sub.columns,sub['grade'])
# a special dict object
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
print(pd.DataFrame(data))
# straightly from 2 dimensions numpy
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

   grade number
a    100      1
b     99      2
c     99      3 Index(['a', 'b', 'c'], dtype='object') Index(['grade', 'number'], dtype='object') a    100
b     99
c     99
Name: grade, dtype: int64
   a  b
0  0  0
1  1  2
2  2  4


,foo,bar
a,0.356753,0.280935
b,0.542696,0.140924
c,0.802197,0.074551


In [ ]:
#index: unalterable,repetitive,usually represent the object(columns represent the feature), just the order of data.
ind=pd.Index([2,1,2])
# we don't use it usually

### indexing
we usually use loc,iloc to index the specific place(remember index is a kind of harsh list, the index often refers to that kind of thing)

In [34]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data1 = pd.Series(['a', 'b', 'c'])
print(data,data1)
print(data[1],data[1:3])
print(data1[1],data1[1:3])
# index is harsh things, if you don't say the index,it will be default 0-n
print(sub['grade'],sub.grade,sub['grade'] is sub.grade)
# loc refers to explicit index(the name of index), iloc refers to implicit index(the number\place of the index)
print(data.iloc[1:3]) #the correspond order(the second to the fourth)
print(data.loc[1:3]) #the value of index (1-3)
# moreover we can use boolen logic to choose the data
print(sub.loc[sub.grade>99,['number']]) 

1    a
3    b
5    c
dtype: object 0    a
1    b
2    c
dtype: object
a 3    b
5    c
dtype: object
b 1    b
2    c
dtype: object
a    100
b     99
c     99
Name: grade, dtype: int64 a    100
b     99
c     99
Name: grade, dtype: int64 True
3    b
5    c
dtype: object
1    a
3    b
dtype: object
  number
a      1


### operation
similar to Numpy,but keep the index and column, and automatically aligns the labels  
and we should pay attention to the NaN values,that may make undefined operation

In [ ]:
rng=np.random.RandomState(42)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
print(np.sin(df * np.pi / 4))
# index alignment:the operation guarantee the alignment of index,so need to see if the index is correpond,or need to deal with the NaN values
area = pd.Series({'bj':400,'gz':300},name='area')
population=pd.Series({'bj':1000,'shh':300},name='population')
print(population / area )
a=pd.Series(np.arange(3),index=[0,1,2])
b=pd.Series(np.arange(3),index=[1,2,3])
print(a+b)
print(a.add(b,fill_value=0))
# as for operation between Series and DataFrame, we use broadcast as well
print(df-df.loc[0],df-df.loc[0][0]) # careful we have to use .loc for pd

          A             B         C             D
0 -1.000000  7.071068e-01 -0.707107  1.224647e-16
1 -1.000000  7.071068e-01  1.000000 -1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01
bj     2.5
gz     NaN
shh    NaN
dtype: float64
0    NaN
1    1.0
2    3.0
3    NaN
dtype: float64
0    0.0
1    1.0
2    3.0
3    2.0
dtype: float64
   A  B  C  D
0  0  0  0  0
1  0  6 -5  2
2  1  1 -4  3    A  B  C  D
0  0 -3  1 -2
1  0  3 -4  0
2  1 -2 -3  1


C:\Users\bytt\AppData\Local\Temp\ipykernel_8324\2485050000.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df-df.loc[0],df-df.loc[0][0])


In [59]:
# deal with missing data:none&nan,nan is the most used,the operation return nan rather than false(in pandas, we can use NA to represent better one)
print(1+np.nan)
val=pd.Series([1,np.nan,2])
print(np.sum(val)) # already changed to nansum
df.iloc[0,0]=np.nan
print(df.isnull())
print(df.dropna())
print(df.dropna(axis=1))
print(df.dropna(how='all'))
print(df.dropna(how='any'))

nan
3.0
       A      B      C      D     0
0   True  False  False  False  True
1  False  False  False  False  True
2  False  False  False  False  True
Empty DataFrame
Columns: [A, B, C, D, 0]
Index: []
   B  C  D
0  3  7  4
1  9  2  6
2  4  3  7
     A  B  C  D   0
0  NaN  3  7  4 NaN
1  6.0  9  2  6 NaN
2  7.0  4  3  7 NaN
Empty DataFrame
Columns: [A, B, C, D, 0]
Index: []


operation for nan:  
> - ``isnull()``: Generate a boolean mask indicating missing values
> - ``notnull()``: Opposite of ``isnull()``
> - ``dropna()``: Return a filtered version of the data(delete all the nan value and keep the square form),we can use how,thread to deal with it
> - ``fillna()``: Return a copy of the data with missing values filled or imputed

## summmary for pandas
pandas is a kind of library that can be used to process sheets data in matrix way(kind of similar to matlab)
1. DataFrame: usually,we use index refer objects, and columns refers to features.usually the index is harsh list, default nature number(can be set initially)
2. as for the index, we usually just use the loc(precisely demostrate the place)
3. the opeartion keeps the index aligned, so need to deal with the lack of value(fill_value)  
we can use the specific func can customize on different basis(fill_value,axis),also the broadcast can be used to fix it.